### PR TITLE
Make json-compilation-database reporter working with oclint-json-compilation-database (0.9dev)

### PR DESCRIPTION
**Pull request by iKiKi**
Make `json-compilation-database` reporter compatible with `oclint-json-compilation-database` (0.9dev) :
  - "directory" and "file" are consistent (compliant with the [format spec](http://clang.llvm.org/docs/JSONCompilationDatabase.html))
  - compilation command is compatible (include a pch file path correction)
  - handle paths containing spaces, e.g. : .../Core\ Data/...
  - updated specs

### CODE REVIEW

**Comment by iKiKi** [comment]
@AliSoftware : Ruby 1.8.7 doesn't support regular expression lookbehind assertions. I missed that, sorry. Thanks for your support with lookbehind' regex.
commit [cd1bcd3](https://github.com/iKiKi/xcpretty/commit/cd1bcd3a32d6f6180614be33b35c11828df436ca) reviews regex with lookbehind assertions and add some specs to test compile directive including spaces in paths.
I also relaunched in my terminal xcpretty and oclint analysis... still wortking with:
```
OCLint version 0.9dev.
Built Jun 17 2014 (03:37:13)
```

**Comment by supermarin** [comment]
@iKiKi @AliSoftware thank you guys for your work!
I've skimmed over the changes, and it seems ok except the Swift comment.
Pinging @kattrali in case I've missed something

**Comment by kattrali** [comment]
Looks good to me. Nice work, @iKiKi! I'd agree that we might need to check for [swift support](https://github.com/iKiKi/xcpretty/commit/cd1bcd3a32d6f6180614be33b35c11828df436ca#diff-e57dc5211b8d88d3b6cb00df3c4eb3f0R44) but I'm otherwise good with the changes.

**Comment by AliSoftware** [comment]
As the actual state of the project does not support Swift yet (the RegExes were already only listing extensions for ObjC & C++), maybe we could merge this PR, and have another dedicated issue to add Swift support (which would probably need separate work with dedicated specs and reviewing every regex)?

**Comment by supermarin** [comment]
@AliSoftware you're actually right - we've added Swift support but only for syntax highlighting.
Thanks for your thoughts!

**Pull request merged**
