### PR TITLE
Custom Reporters

### LINKED ISSUE #199: Custom Reporter
Just like custom formatters can be specified by a command line flag, custom reporters should be able to as well. The 3 provided are a great start, but creating custom ones will allow xcpretty to hook up with more services, especially ones that use an API and expect a certain output.

### PR DESCRIPTION
**Pull request by mtitolo**
Fixes #199. Sorry this took so long, it's been stuck in OSS review for several weeks.

This adds custom reporter functionality. The `-r` flag now accepts and loads paths. Current reporters now inherit from the base Reporter class.

### CODE REVIEW

**Comment by kattrali** [comment]
Looks good to me :+1:

**Comment by vhbit** [comment]
Any updates on this? I'd be glad to see it moving forward as absence of custom reporters (or actually just Phabricator one) is the only thing which keeps us on using `xctool` instead of `scan@fastlane`.

**Comment by mtitolo** [comment]
Is there anything else that needs to get done for this to get in?

**Comment by supermarin** [comment]
@mtitolo not from our side if you're ready @mtitolo :)

@kattrali ?

**Pull request merged**
