### PR TITLE
Fix bug whereby syntax highlighting was being performed in non-colori…

### PR DESCRIPTION
**Pull request by rasharab**
…ze mode

Was producing cruft of bad output for our console logs on our build machines.

### CODE REVIEW

**Comment by justinseanmartin** [comment]
CC: @supermarin 

Would love to see this merged, we're running into the same thing after bumping versions from a really old version of the gem.

**Comment by supermarin** [comment]
@rasharab @justinseanmartin are you running `xcpretty` with `--no-color` explicitly?

**Comment by justinseanmartin** [comment]
Yes, we're explicitly passing `--no-color`, as Jenkins doesn't support color codes by default. 

We considered installing the colored text output Jenkins plugin, but were concerned with how long it might take to render some of our larger logs. We plan to test and roll this out at some point in the future.

**Comment by justinseanmartin** [comment]
@supermarin ping! :wink:

**Comment by stanislaw** [comment]
+1 and ping!

**Comment by danielribeiro** [comment]
Hey @supermarin, do you need anything else to merge this?

**Comment by kattrali** [comment]
Looked good to me ¯\_(ツ)_/¯

**Pull request merged**
