### PR TITLE
Add support to parse parallel iOS simulator output

### PR DESCRIPTION
**Pull request by lyndsey-ferguson**
Parses a log file that was created by consolidating log files from multiple simulators run by Xcode 9.

### CODE REVIEW

**Comment by lyndsey-ferguson** [comment]
Please advise on the PR: I do not have output from multiple simulators run directly from Xcode, rather I am using consolidated output from multiple simulators that is managed by `bluepill` running Xcode 9 and am not sure if this is the same type of logging. My guess is that when running Xcode 9 directly from the console, the test and test suite "start" and "passed|failed" console messages would be interweaved due to parallel sims writing to the console.

**Comment by niveus** [comment]
I'm still seeing 0 test results with this branch. 
```
+--------------------+---+
|      Test Results      |
+--------------------+---+
| Number of tests    | 0 |
| Number of failures | 0 |
+--------------------+---+
```

**Comment by lyndsey-ferguson** [comment]
@niveus can you post your log file? I don't have logs of Xcode 9 with multiple simulators.

**Comment by wessmith** [comment]
@lyndsey-ferguson here's a log file with two destinations `iPhone 6s,OS=10.2` and `iPhone 7,OS=11.0`

[xcodebuild-iphone6s-and-iphone7.log](https://github.com/supermarin/xcpretty/files/1353507/xcodebuild-iphone6s-and-iphone7.log)

Interestingly, I don't see any way to differentiate between OS versions in the log when two destinations are the same device type (e.g. `iPhone 6s,OS=10.2` and `iPhone 6s,OS=11.0`). I'll attach the output from that as well shortly.

**Comment by lyndsey-ferguson** [comment]
Thank you. As I suspected, the output is quite different from the output of `bluepill` running multiple simulators. As this is not a valid PR for the normal flow, I am closing this PR.

**Comment by RomanTysiachnik** [comment]
@lyndsey-ferguson How to get that support then? Is there a way to use bluepill instead xcpretty?

**Comment by lyndsey-ferguson** [comment]
If you use the [`bluepill` command line tool](https://github.com/linkedin/bluepill) it will provide you some reporting. I stopped using it as it was not giving me the reporting I needed, but there have been some updates since my departure and I will check it out again to see if has improved.

**Comment by ykhandelwal913** [comment]
@lyndsey-ferguson is this supported added?

**Comment by lyndsey-ferguson** [comment]
@ykhandelwal913 I am not aware of any parallel processing being performed by xcpretty: I am not a contributor.

**Pull request closed without merging**
