### PR TITLE
Fix 291 tests restarting when fatal error

### PR DESCRIPTION
**Pull request by kenji21**
see issue #291

### CODE REVIEW

**Comment by kenji21** [comment]
Well...

 Scenario: Performance                                        # features/xcpretty.feature:11
    When I run xcpretty over a big file                        # features/steps/xcpretty_steps.rb:9
    Then the performance should be way faster than running cat # features/steps/xcpretty_steps.rb:27
      XCPretty run time: 2.053025391
      expected: < 2
           got:   2.053025391 (RSpec::Expectations::ExpectationNotMetError)


I have run this test using : 

````
cucumber features/xcpretty.feature:11
````

On both a clone from openium:fix-291-tests-restarting-when-fatal-error / supermarin:master  and I got nearly same results: 

````
git remote -v
origin	https://github.com/supermarin/xcpretty (fetch)
origin	https://github.com/supermarin/xcpretty (push)
kenji@macboo:~/Desktop/xcpretty [master]
for i in $(seq 1 10) ; do cucumber features/xcpretty.feature:11 |grep "XCPretty run time" ; done
      XCPretty run time: 1.551599
      XCPretty run time: 1.508241
      XCPretty run time: 1.504924
      XCPretty run time: 1.533558
      XCPretty run time: 1.543447
      XCPretty run time: 1.666644
      XCPretty run time: 1.532642
      XCPretty run time: 1.570571
      XCPretty run time: 1.539974
      XCPretty run time: 1.632162
kenji@macboo:~/Desktop/xcpretty [master] 
git log -1
commit 93b6f872c322d963b0ad399d67c9d638940baa5e
````

````
git remote -v
origin	https://github.com/openium/xcpretty (fetch)
origin	https://github.com/openium/xcpretty (push)
upstream	https://github.com/supermarin/xcpretty (fetch)
upstream	https://github.com/supermarin/xcpretty (push)
kenji@macboo:~/github/xcpretty [fix-291-tests-restarting-when-fatal-error]
for i in $(seq 1 10) ; do cucumber features/xcpretty.feature:11 |grep "XCPretty run time" ; done
      XCPretty run time: 1.530221
      XCPretty run time: 1.665705
      XCPretty run time: 1.505739
      XCPretty run time: 1.545439
      XCPretty run time: 1.552653
      XCPretty run time: 1.573913
      XCPretty run time: 1.498432
      XCPretty run time: 1.533834
      XCPretty run time: 1.498154
      XCPretty run time: 1.583827
kenji@macboo:~/github/xcpretty [fix-291-tests-restarting-when-fatal-error]
git log -1
commit 07e02bbfafba810f6cb53fdcb48a7b75e64d50fe
````

So performances are nearly the sames...

I don't understand how to keep the performances below 2 seconds on Travis to make CI happy

**Comment by supermarin** [comment]
Thank you for the contribution @kenji21

**Comment by barakwei** [comment]
@supermarin when can we expect an official version with this fix?

**Comment by kenji21** [comment]
@barakwei waiting the release, I use a local copy pointing the fix branch, not ideal, but it's temporary :

````
hudson@imacci:~/xcpretty [fix-291-tests-restarting-when-fatal-error]                                                                                                                                                                                             git status
On branch fix-291-tests-restarting-when-fatal-error
Your branch is up-to-date with 'origin/fix-291-tests-restarting-when-fatal-error'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	xcpretty

nothing added to commit but untracked files present (use "git add" to track)
hudson@imacci:~/xcpretty [fix-291-tests-restarting-when-fatal-error]                                                                                                                                                                                             cat xcpretty
#!/bin/sh
BASEDIR=$(dirname $0)

set -x
ruby -rubygems -I $BASEDIR/lib $BASEDIR/bin/xcpretty "$@"
````

**Comment by barakwei** [comment]
@kenji21 I use [specific_install](https://github.com/rdp/specific_install) myself, but as you said, this is not optimal.

**Pull request merged**
