### PR TITLE
Correcting the way Xcode 8 XCUITest failures are parsed

### PR DESCRIPTION
**Pull request by ashgti**
This is a pull request for #234

### CODE REVIEW

**Comment by jameseisenhauer** [comment]
hopefully this will come in soon but in the mean time all my reports are Green!!

**Comment by supermarin** [comment]
@ashgti looks great, thanks!

**Comment by krzysztofkempa** [comment]
@supermarin Hello! Could you tell me please when do you plan to release new version (0.2.3)? 
Regards

**Comment by supermarin** [comment]
@krzysztofkempa released just now

**Comment by krzysztofkempa** [comment]
@supermarin Thank you!

**Comment by samskiter** [comment]
this got reverted?

**Comment by supermarin** [comment]
nope

**Comment by abhiramkrishnan** [comment]
@supermarin : Hi! Still see the same issue with 0.2.4. Appears to be reverted here just before the 0.2.4 release?
https://github.com/supermarin/xcpretty/commit/28a56ab8920e0f683b689c7f8548bc05b8aa6806

**Comment by dreampiggy** [comment]
Hi, it seems that some expcetion during test case, for example, a SIGABRT or something crash by C function(such as `free(0)`) will also be ommited in the `xcpretty -c` output. I have to check the raw stdout and stderr log to find the issue. Could you please help to find any better solution ?

For normal fail reason(Exception, assert), it can format the fail reason. Thanks for all of constributors

**Pull request merged**
