### PR TITLE
Improve Code sign error checking

### PR DESCRIPTION
**Pull request by Mitko-Kerezov**
Upon a missing Provisioning profile/Code sign identity, the following errors are thrown (using Xcode 8):
missing Provisioning profile:

```
MyProject requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
```

missing Code sign identity:

```
No certificate matching 'iPhone Distribution: Name (XXXXXXXXXX)' for team 'XXXXXXXXXX':  Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
```

From those errors `Code signing is required for product type 'Application' in SDK 'iOS 10.0'` is already captured thanks to https://github.com/supermarin/xcpretty/pull/247. But the other two errors seem to be missing.

I've tried adding unit tests too, ping @supermarin for thoughts on this

### CODE REVIEW

**Comment by Mitko-Kerezov** [comment]
@supermarin I'm having trouble deciphering why the CI tests are failing

**Comment by supermarin** [comment]
@Mitko-Kerezov sorry for the delay, `master` was broken. If you rebase now it should be green

**Comment by Mitko-Kerezov** [comment]
Hey @supermarin - I got around to fixing the conflicts but a performance test failed - anything I can do about that 💭

**Comment by supermarin** [comment]
Try rerunning a couple times; although looking at the code, I suspect this Regex is too slow (not specific enough at the line start)

``` ruby
PROVISIONING_PROFILE_REQUIRED_MATCHER = /^(.*requires a provisioning profile.*)$/
```

**Comment by mbektchiev** [comment]
Besides the errors described by @Mitko-Kerezov we've added two more that occur when using Swift with an incorrect project settings:

> `Swift is unavailable on iOS earlier than 7.0; please set IPHONEOS_DEPLOYMENT_TARGET to 7.0 or later (currently it is '6.0').` 

and 
> `“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.`
> 
>

**Comment by mbektchiev** [comment]
@supermarin Can you please review and merge if everything is OK?

**Comment by supermarin** [comment]
Thanks @mbektchiev !

**Comment by Mitko-Kerezov** [comment]
Ping @supermarin will `0.2.6` be released soon as we kind of need this fix

**Pull request merged**
