### PR TITLE
Fixed COMPILE_MATCHER to match all languages

### PR DESCRIPTION
**Pull request by pcantrell**
The existing COMPILE_MATCHER pattern only matches `CompileC`, and fails to match `CompileSwift`.

The new pattern matches `CompileFollowedByAnyLettersAndDigits`.

### CODE REVIEW

**Comment by pcantrell** [comment]
Hound’s warning about line length was present _before_ the change, so … not a problem?

**Comment by supermarin** [comment]
@pcantrell not a problem.

Thanks for the contribution!
Do you mind writing a test in `parser_spec.rb` that shows it failing?

**Comment by pcantrell** [comment]
> Do you mind writing a test in parser_spec.rb that shows it failing?

Done.

The old spec had been testing Swift just by making a little substitution in the C compiler invocation, but the real-life output of Swift compilation is quite different from C, so I added a separate fixture for it.

**Comment by supermarin** [comment]
Thanks @pcantrell!

**Pull request merged**
