### PR TITLE
Improve screenshot support

### PR DESCRIPTION
**Pull request by mattcotton**
Screenshots are now shown against their respective test - requires screenshot filenames to start with the name of the test, not the test class.

### CODE REVIEW

**Comment by mattcotton** [comment]
@supermarin this is ready now - seem to have some CI issues that are not related to my change?

**Comment by supermarin** [comment]
I think Rubygems is down - let's check in a few hours.

Thank you for all your work here @mattcotton !

**Comment by aditjain** [comment]
Hey guys - any updates?

**Comment by mattcotton** [comment]
Even once @supermarin merges this, it won't be available as an upgrade until 0.27 is released. If you need this urgently, you can pull down my branch/fork and build the gem from there.

**Comment by aditjain** [comment]
I created gem based of your fork and i can see the changes working. :) Thank you so much!!!

**Comment by mattcotton** [comment]
Glad it helped you, @aditjain.

@supermarin can we re-run CI for this?

**Comment by supermarin** [comment]
Sorry guys, I was out the past few days.
Will rerun this today and try to get it merged / released. stay tuned

**Comment by aditjain** [comment]
@mattcotton @supermarin is this one part of 0.2.7 or 0.2.8?

**Comment by mattcotton** [comment]
Looks to be part of 0.28

**Pull request merged**
