### PR TITLE
Support Aggregate Targets

### PR DESCRIPTION
**Pull request by dflems**
In the process of writing a custom formatter, I noticed that there was no support for aggregate targets. This PR covers the general case. The xcodebuild output is identical to `BUILD TARGET` but says `BUILD AGGREGATE TARGET` instead.

### CODE REVIEW

**Comment by kattrali** [comment]
Looks good to me :+1:

**Comment by supermarin** [comment]
LGTM

If you wouldn't mind writing a `feature`, you'll get another :100:

**Comment by dflems** [comment]
@supermarin ^^ I'm new to writing cucumber tests but they seem in line with the other ones.

**Comment by supermarin** [comment]
@dflems thank you very much Sir.

I left you inline notes just to delete the extra ones, then we're ready to :shipit:

**Comment by dflems** [comment]
@supermarin: Done. Sorry about that. It looked like those cases weren't covered in `features`.

**Comment by supermarin** [comment]
@dflems :100: !

**Pull request merged**
